channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.3.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==1.26.2
  - pathlib==1.0.1
  - psutil==5.9.8
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
