services:
  app:
    build:
      context: ./ml_pipeline
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:  
      - backend
    networks:
      - mlops-network

  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mlops-network

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__FERNET_KEY: "fernet_key_here"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    networks:
      - mlops-network

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
