version: '3.8'

services:
  app:
    # image: ml_image:latest
    build:
      context: ../ml_pipeline
      dockerfile: Dockerfile
    ports:
      - "5011:5011"
    environment:
      - MLFLOW_TRACKING_URI=http://docker-mlflow-1:5001 
    depends_on:  
      - backend
      - mlflow
    networks:
      - mlops-network

  backend:
    # image: backend_image:latest
    build:
      context: ../backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mlops-network

  airflow:
    # image: airflow_image:latest
    build:
      context: ../airflow
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__FERNET_KEY: "z3T8GKlr2ldSvyfoweOXCiiyOrB4h_-WF_9CDM06yoY="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@db:5432/airflow"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - db
    networks:
      - mlops-network

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - mlops-network

  mlflow:
    # image: bitnami/mlflow:latest
    build:
      context: ../mlflow
      dockerfile: Dockerfile
    # command: /opt/bitnami/python/bin/mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow-artifacts
    environment:
      MLFLOW_TRACKING_URI: "http://docker-mlflow-1:5001"
    ports:
      - "5001:5000"
    volumes:
      - mlflow-data:/mlflow-artifacts
    networks:
      - mlops-network
    depends_on:
      - db

networks:
  mlops-network:
    driver: bridge


volumes:
  mlflow-data:
    driver: local